# to tell to ingress controller how to handle incoming requests by specifying the rules
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    # The nginx controller will scan all different config files in my cluter to find the one which has this annotations to udnerstand that the routing rules are here 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: liveticketz.dev
      http:
        paths:
          - path: /auth/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000